name: test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - run: npm run lint
      - run: npm test
      - name: save coverage comment
        uses: MishaKav/jest-coverage-comment@v1.0.23
        with:
          coverage-summary-path: ./coverage/coverage-summary.json
